### ISSUE TITLE
Doesn't do anything

### ISSUE THREAD

**Issue by apoleo88** [ngthailam/flutter_app_short_cut#2]
Tried your example and it doesn't do anything when the function is launched, no error was triggered.

```
FlutterAppShortcut().push(
      ShortcutArg(
        id: 'id_1',
        shortLabel: 'Home page',
        longLabel: 'Go to Home page',
        iconResourceName: 'app_icon',
        uri: 'https://www.google.com',
        enabled: true,
      )
    );
```

Tested on Android device with SDK 32
```
Flutter 2.10.4 • channel stable
Tools • Dart 2.16.2 • DevTools 2.9.2
```

**Comment by ngthailam** [comment]
Check pub dev version for release `0.2.1` 
Or you can temporarily remove `iconResourceName: 'app_icon',` or add the resource to the res folder as per the example
